"""js_lib 셀렉터 단일화 리팩토링 동등성 고정 — 원본 문자열 스냅샷.

PICKER_* 9종은 "최근 열린 non-법인카드 k-window" 탐색 프리앰블을 복붙 공유하고,
MENU_CHECK_JS 는 detection 의 다이얼로그 셀렉터 목록을 별도 하드코딩하고 있었다.
이를 빌더/공유 상수로 모으는 리팩토링이 **생성 결과를 한 글자도 바꾸지 않음**을
보증하기 위해, 리팩토링 직전 원본을 여기 그대로 고정한다(자동 스냅샷 생성).
"""

from __future__ import annotations

from nbkit.browser import detection
from nbkit.omnisol import js_lib

# ── 리팩토링 직전 원본(2026-07-31 스냅샷) ──────────────────────────────────────
_ORIGINALS = {
    'PICKER_SEARCH_JS': "(q) => {\n  const c = s => String(s==null?'':s).replace(/\\s+/g,' ').trim();\n  const p = [...document.querySelectorAll('.k-window')].filter(w=>w.offsetParent!==null)\n    .filter(w=>!/법인카드/.test(c((w.querySelector('.k-window-title')||{}).innerText))).slice(-1)[0];\n  if (!p) return { ok:false, reason:'no-pop' };\n  // 팝업별 검색창 id 상이: 예산단위/계정=#keyword, 프로젝트=#s_search_key, 거래처=#customTextBox.\n  // 알려진 id 우선(card 동작 보존), 없으면 search_key/keyword/customText 접미·접두 → 첫 보이는 text input.\n  const kw = p.querySelector('#keyword') || p.querySelector('#s_search_key')\n    || p.querySelector('#customTextBox') || p.querySelector('[id$=search_key]')\n    || p.querySelector('[id*=keyword]') || p.querySelector('[id*=customText]')\n    || [...p.querySelectorAll('input')].filter(i=>i.offsetParent!==null && (i.type==='text'||!i.type))[0];\n  if (!kw) return { ok:false, reason:'no-keyword' };\n  const d = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value'); d.set.call(kw, q);\n  ['input','change'].forEach(t => kw.dispatchEvent(new Event(t, { bubbles:true })));\n  // ⚠ focus 필수 — 이후 page.keyboard.press('Enter')가 이 검색창에 도달해야 서버 재조회가 뜬다.\n  // 셀 에디터(showEditor)로 연 팝업(거래처 customTextBox 등)은 포커스가 그리드 캔버스에 있어\n  // focus 없이 Enter 를 누르면 검색이 트리거되지 않는다(프로브 trip_probe3 실측 2026-07-06).\n  kw.focus();\n  return { ok:true, field: kw.id || '(no-id)' };\n}",
    'PICKER_READ_JS': "([codeField, nameField, limit]) => {\n  const c = s => String(s==null?'':s).replace(/\\s+/g,' ').trim();\n  const p = [...document.querySelectorAll('.k-window')].filter(w=>w.offsetParent!==null)\n    .filter(w=>!/법인카드/.test(c((w.querySelector('.k-window-title')||{}).innerText))).slice(-1)[0];\n  if (!p) return { rows:-1, reason:'no-pop' };\n  try { const g = window.jQuery(p.querySelector('.dews-ui-grid')).data('dewsControl')._grid;\n    const n = g.getDataSource().getRowCount(); const out = [];\n    for (let i=0; i<Math.min(n, limit||n); i++) out.push({\n      i, code: String(g.getValue(i, codeField)), name: String(g.getValue(i, nameField)) });\n    return { rows:n, options: out };\n  } catch(e) { return { rows:-1, err:String(e).slice(0,60) }; }\n}",
    'PICKER_READ_MULTI_JS': "([fields, limit]) => {\n  const c = s => String(s==null?'':s).replace(/\\s+/g,' ').trim();\n  const p = [...document.querySelectorAll('.k-window')].filter(w=>w.offsetParent!==null)\n    .filter(w=>!/법인카드/.test(c((w.querySelector('.k-window-title')||{}).innerText))).slice(-1)[0];\n  if (!p) return { rows:-1, reason:'no-pop' };\n  try { const g = window.jQuery(p.querySelector('.dews-ui-grid')).data('dewsControl')._grid;\n    const ds = g.getDataSource();\n    const n = ds.getRowCount();\n    const rows = ds.getJsonRows(0, n-1);\n    const cap = limit || rows.length;\n    const out = rows.slice(0, Math.min(rows.length, cap)).map((r,i)=>{\n      const o = { i }; for (const f of fields) o[f] = r[f]==null?null:String(r[f]); return o; });\n    return { rows:n, options: out };\n  } catch(e) { return { rows:-1, err:String(e).slice(0,80) }; }\n}",
    'PICKER_SELECT_JS': "(row) => {\n  const c = s => String(s==null?'':s).replace(/\\s+/g,' ').trim();\n  const p = [...document.querySelectorAll('.k-window')].filter(w=>w.offsetParent!==null)\n    .filter(w=>!/법인카드/.test(c((w.querySelector('.k-window-title')||{}).innerText))).slice(-1)[0];\n  if (!p) return { ok:false, reason:'no-pop' };\n  try { const g = window.jQuery(p.querySelector('.dews-ui-grid')).data('dewsControl')._grid;\n    g.setCurrent({ itemIndex: row, fieldName: g.getColumns()[1].fieldName });\n    g.setSelection({ startRow: row, endRow: row, startColumn: 0, endColumn: 0 });\n    return { ok:true };\n  } catch(e) { return { ok:false, err:String(e).slice(0,60) }; }\n}",
    'PICKER_CLOSE_JS': "() => {\n  const c = s => String(s==null?'':s).replace(/\\s+/g,' ').trim();\n  const p = [...document.querySelectorAll('.k-window')].filter(w=>w.offsetParent!==null)\n    .filter(w=>!/법인카드/.test(c((w.querySelector('.k-window-title')||{}).innerText))).slice(-1)[0];\n  if (!p) return false;\n  const x = p.querySelector('.k-i-close, .k-window-action, [aria-label*=Close], [title*=닫기]');\n  if (x) { x.click(); return true; }\n  const b = [...p.querySelectorAll('button')].filter(e=>e.offsetParent!==null)\n    .find(e => /닫기|취소|close/i.test(c(e.innerText)));\n  if (b) { b.click(); return true; }\n  return false;\n}",
    'PICKER_APPLY_BTN_JS': "() => {\n  const c = s => String(s==null?'':s).replace(/\\s+/g,' ').trim();\n  const p = [...document.querySelectorAll('.k-window')].filter(w=>w.offsetParent!==null)\n    .filter(w=>!/법인카드/.test(c((w.querySelector('.k-window-title')||{}).innerText))).slice(-1)[0];\n  if (!p) return null;\n  const b = [...p.querySelectorAll('button')].filter(x=>x.offsetParent!==null).find(x=>/적용|확인|선택/.test(c(x.innerText)));\n  if (!b) return null; const r = b.getBoundingClientRect();\n  return { x: Math.round(r.x+r.width/2), y: Math.round(r.y+r.height/2), text:c(b.innerText) };\n}",
    'PICKER_GRID_RECT_JS': "() => {\n  const c = s => String(s==null?'':s).replace(/\\s+/g,' ').trim();\n  const p = [...document.querySelectorAll('.k-window')].filter(w=>w.offsetParent!==null)\n    .filter(w=>!/법인카드/.test(c((w.querySelector('.k-window-title')||{}).innerText))).slice(-1)[0];\n  if (!p) return null;\n  const g = p.querySelector('.dews-ui-grid'); if (!g) return null;\n  const r = g.getBoundingClientRect();\n  return { x: Math.round(r.x + r.width/2), y: Math.round(r.y + r.height/2) };\n}",
    'PICKER_ROWCOUNT_JS': "() => {\n  const c = s => String(s==null?'':s).replace(/\\s+/g,' ').trim();\n  const p = [...document.querySelectorAll('.k-window')].filter(w=>w.offsetParent!==null)\n    .filter(w=>!/법인카드/.test(c((w.querySelector('.k-window-title')||{}).innerText))).slice(-1)[0];\n  if (!p) return -1;\n  try { const g = window.jQuery(p.querySelector('.dews-ui-grid')).data('dewsControl')._grid;\n    return g.getDataSource().getRowCount(); } catch(e) { return -2; }\n}",
    'PICKER_FOCUS_LAST_JS': "() => {\n  const c = s => String(s==null?'':s).replace(/\\s+/g,' ').trim();\n  const p = [...document.querySelectorAll('.k-window')].filter(w=>w.offsetParent!==null)\n    .filter(w=>!/법인카드/.test(c((w.querySelector('.k-window-title')||{}).innerText))).slice(-1)[0];\n  if (!p) return { ok:false, reason:'no-pop' };\n  try { const gridEl = p.querySelector('.dews-ui-grid');\n    const g = window.jQuery(gridEl).data('dewsControl')._grid;\n    const n = g.getDataSource().getRowCount();\n    const cols = g.getColumns();\n    const f = (cols.find(x=>x.visible) || cols[1] || cols[0]).fieldName;\n    g.setCurrent({ itemIndex: n-1, fieldName: f });\n    const focusable = gridEl.querySelector('[tabindex], canvas, .k-grid-content') || gridEl;\n    focusable.focus && focusable.focus();\n    return { ok:true, row: n-1 };\n  } catch(e) { return { ok:false, err: String(e).slice(0,100) }; }\n}",
    'MENU_CHECK_JS': "() => {\n  const grids = document.querySelectorAll('.dews-ui-grid').length;\n  const dlg = [...document.querySelectorAll('.k-window, [role=dialog], .modal')].find(x => x.offsetParent !== null);\n  const popup = dlg ? (dlg.innerText || '').trim() : '';\n  const notFound = /찾을 수 없|권한이 없|접근/.test(popup) && /메뉴|모듈/.test(popup);\n  return { grids, notFound, popup: popup.replace(/\\n+/g, ' ').slice(0, 50) };\n}",
}

_ORIGINAL_DIALOG_SELECTORS = '.k-window, [role=dialog], .modal'


def test_picker_and_menu_js_byte_identical_to_originals():
    # 빌더 생성 결과가 검증된 원본과 byte 단위로 동일해야 한다(기능 동일성의 최강 보증).
    for name, original in _ORIGINALS.items():
        assert getattr(js_lib, name) == original, f"{name} 가 원본과 달라짐"


def test_dialog_selectors_shared_constant():
    # detection 과 MENU_CHECK_JS 가 같은 다이얼로그 목록을 공유한다(별도 하드코딩 금지).
    assert detection.DIALOG_SELECTORS == _ORIGINAL_DIALOG_SELECTORS
    assert detection.DIALOG_SELECTORS in js_lib.MENU_CHECK_JS
